name: "cli-action"

description: "Runs Seal CLI on a target directory"

author: "Seal Community"

branding:
  icon: "thumbs-up"
  color: "blue"

inputs:
  version:
    description: "CLI version to use, same as a tag - e.g. v0.1.0; empty will use latest"
    default: ""
  target:
    description: "Target dir"
    default: "."
  mode:
    description: "Fix or scan; scan requires sealtoken as env"
    default: "scan"
  verbosity:
    description: "Verbosity: v, vv, vvv"
    default: "vv"
  summary:
    description: "Path to summary file, by default does not generate; only relevant for 'fix' mode"
    default: ""
  project:
    description: "Used as part of cli authentication for fix command, can be any* value"
    default: "ci"
  CLI_TOKEN:
    required: false # required for fix mode
    description: "Same token used by npm client. Usually called SEAL_NPM_TOKEN (without the project)"

runs:
  using: "composite"
  steps:
    - name: "Download CLI - Other"
      if: runner.os != 'Linux'
      shell: bash
      run: |
        echo "::error::Unsupported runner os: ${{ runner.os }}"
        exit 1
    - name: "Download CLI - Linux"
      id: download
      shell: bash
      if: runner.os == 'Linux'
      env:
        GH_TOKEN: ${{ github.token }}
        cli-repo: "seal-community/cli"
      run: |
        ZIP_NAME="seal-linux-amd64*.zip" # wildcard to support version in asset name
        # not concurrent-safe for multiple jobs
        echo "Downloading zip ${ZIP_NAME}"
        gh --repo "${{ env.cli-repo }}" release download "${{ inputs.version }}" -p "${ZIP_NAME}" --output "${{ runner.temp }}/${ZIP_NAME}"
        unzip ${{ runner.temp }}/${ZIP_NAME} -d ${{ runner.temp }}
        echo "cli_path=${{ runner.temp }}/seal" >> ${GITHUB_OUTPUT}
        ${{ runner.temp }}/seal version
    - name: "Run CLI"
      shell: bash
      run: |
        echo "Running cli from ${{ steps.download.outputs.cli_path }}"
        SUMMARY_PARAM=""
        if [[ "${{ inputs.summary}}" != "" ]] && [[ "${{ inputs.mode }}" == "fix" ]]; then
            SUMMARY_PARAM="--summarize ${{ inputs.summary}}"
        fi
        SEAL_TOKEN=${{ inputs.CLI_TOKEN }} ${{ steps.download.outputs.cli_path }} -${{ inputs.verbosity }} ${{ inputs.mode }} ${{ inputs.target }} ${SUMMARY_PARAM}

